{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cjjc.lib_catch",
    "module": "lib_catch",
    "version": "0.0.1-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lib_catch-0.0.1-RELEASE.aar",
          "url": "lib_catch-0.0.1-RELEASE.aar",
          "size": 84731,
          "sha512": "84cbfa15268efe1c3fc321b46622d7884d019c77a19e9311c22d01e5850dc54b37004312588fdcbd8c931765354248d7d14705a7f3a8cbee08e859ffe2997b15",
          "sha256": "d32e7833b1c0b98b57acb0c56b8ee219abd70cdde1bd3a30acab5d9440002a45",
          "sha1": "302113b5574337b37c0283a44901cb02d2b4a691",
          "md5": "79c821a84b8d037bbad86a939c4b0f4d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.cjjc.lib_tools",
          "module": "lib_tools",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "lib_catch-0.0.1-RELEASE.aar",
          "url": "lib_catch-0.0.1-RELEASE.aar",
          "size": 84731,
          "sha512": "84cbfa15268efe1c3fc321b46622d7884d019c77a19e9311c22d01e5850dc54b37004312588fdcbd8c931765354248d7d14705a7f3a8cbee08e859ffe2997b15",
          "sha256": "d32e7833b1c0b98b57acb0c56b8ee219abd70cdde1bd3a30acab5d9440002a45",
          "sha1": "302113b5574337b37c0283a44901cb02d2b4a691",
          "md5": "79c821a84b8d037bbad86a939c4b0f4d"
        }
      ]
    }
  ]
}
