{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cjjc.lib_network",
    "module": "lib_network",
    "version": "0.0.1-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lib_network-0.0.1-RELEASE.aar",
          "url": "lib_network-0.0.1-RELEASE.aar",
          "size": 168750,
          "sha512": "afe4dee826008442976b7c3c1f334e169516dd082da0c912d6faaf6c98a8706f602a29aca851bd24af46a3f85317e72544978ba330e6a6a18cf445d3defe2b4a",
          "sha256": "c34306abc36af17eeb93840191259d80126ccecf357868a744dd1d8ebb216d71",
          "sha1": "d7fa5275cde29804a09ad11dbe65504a155445c6",
          "md5": "9d8cd7d1e00a55160ffb79718b1c56d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.cjjc.lib_tools",
          "module": "lib_tools",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        },
        {
          "group": "com.github.liujingxing.rxhttp",
          "module": "rxhttp",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.trello",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "com.github.liujingxing.rxlife",
          "module": "rxlife-rxjava3",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.github.liujingxing.rxhttp",
          "module": "converter-fastjson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.42"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib_network-0.0.1-RELEASE.aar",
          "url": "lib_network-0.0.1-RELEASE.aar",
          "size": 168750,
          "sha512": "afe4dee826008442976b7c3c1f334e169516dd082da0c912d6faaf6c98a8706f602a29aca851bd24af46a3f85317e72544978ba330e6a6a18cf445d3defe2b4a",
          "sha256": "c34306abc36af17eeb93840191259d80126ccecf357868a744dd1d8ebb216d71",
          "sha1": "d7fa5275cde29804a09ad11dbe65504a155445c6",
          "md5": "9d8cd7d1e00a55160ffb79718b1c56d8"
        }
      ]
    }
  ]
}
