{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cjjc.lib_catch",
    "module": "lib_catch",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lib_catch-0.0.4-SNAPSHOT.aar",
          "url": "lib_catch-0.0.4-SNAPSHOT.aar",
          "size": 84909,
          "sha512": "36a6ba15f5fefe1b9b852dc138df45538aa53657b7b5498ff8bde0f0fa7a69dd91659d5e6af9d3f8e8e1eea0b72e8281d437567b584c13f90e661b548a2d25ca",
          "sha256": "f050484fac0df1dc00b92e50355dce2021472720893dbfb38edfcfae49ab2d80",
          "sha1": "dba7ea7bbaba08e500d9fcb5df886dd5ca3503e2",
          "md5": "f8262dcf82c565664ff5bc6e9e2ebb13"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.cjjc.lib_tools",
          "module": "lib_tools",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "lib_catch-0.0.4-SNAPSHOT.aar",
          "url": "lib_catch-0.0.4-SNAPSHOT.aar",
          "size": 84909,
          "sha512": "36a6ba15f5fefe1b9b852dc138df45538aa53657b7b5498ff8bde0f0fa7a69dd91659d5e6af9d3f8e8e1eea0b72e8281d437567b584c13f90e661b548a2d25ca",
          "sha256": "f050484fac0df1dc00b92e50355dce2021472720893dbfb38edfcfae49ab2d80",
          "sha1": "dba7ea7bbaba08e500d9fcb5df886dd5ca3503e2",
          "md5": "f8262dcf82c565664ff5bc6e9e2ebb13"
        }
      ]
    }
  ]
}
